In [21]:
import numpy as np
import json


In [2]:
is_inference = False
if not is_inference:
    print('go')
    

go


In [3]:
all_entities_one_hop_1 = [11782, 2063, 15887, 5651, 14872, 21532, 3100, 1056, 34, 12322, 14379, 1580, 5685, 6204, 20039, 1615, 14928, 1621, 7257, 14940, 8810, 20599, 14971, 6281, 18580, 5270, 8854, 16033, 12964, 1190, 1704, 16042, 3249, 8372, 8890, 7358, 20158, 20160, 10433, 7366, 14538, 8920, 4828, 13534, 5859, 20717, 14061, 7407, 4851, 19707, 10491, 766, 11008, 7939, 7427, 9482, 269, 1807, 20754, 15127, 16664, 17688, 282, 21789, 1826, 11573, 13111, 6969, 12606, 14660, 13127, 14663, 20814, 4953, 1882, 13163, 2924, 3949, 7547, 5501, 7550, 382, 2432, 19844, 2437, 5519, 17808, 5013, 22422, 11674, 433, 12218, 18367, 18368, 6081, 18371, 963, 21446, 16331, 21455, 16338, 16375, 9174, 19422, 21485, 17902, 12276, 6647, 4607]

In [4]:
all_entities_one_hop_2=[20994, 3078, 7189, 6678, 9752, 3609, 21023, 15904, 14379, 15413, 4154, 20026, 16957, 17985, 12866, 1606, 20039, 14409, 15433, 13385, 19031, 20571, 16988, 21601, 14950, 11879, 18025, 6253, 5232, 2681, 18042, 14971, 14462, 659, 17564, 16028, 19107, 8360, 5800, 20650, 10419, 1722, 11450, 5825, 19142, 14538, 13003, 6349, 14042, 17116, 12509, 12514, 12515, 19685, 21737, 17645, 14062, 12529, 4851, 6391, 1280, 7939, 1798, 8967, 14599, 1802, 2826, 1807, 17685, 18713, 2846, 8488, 3880, 3882, 21803, 4402, 11582, 10558, 6976, 20289, 16196, 4932, 9548, 16205, 9552, 6491, 8545, 10083, 7523, 5478, 16744, 362, 1394, 9075, 13684, 13182, 21894, 19351, 14236, 3487, 14247, 14760, 6055, 942, 9136, 18869, 12218, 12731, 18366, 19390, 18368, 1472, 2001, 2002, 14801, 11729, 19423, 14304, 13796, 18405, 3557, 13804, 2541, 11761, 3571, 19958]

In [25]:
all_triples_one_hop = [2052, 55302, 51222, 26658, 61475, 57388, 16443, 86077, 30782, 110665, 112715, 22604, 34895, 43092, 14428, 110689, 67682, 36969, 45165, 112750, 100471, 14455, 6265, 30853, 82054, 98440, 65674, 73881, 92315, 49312, 41122, 37029, 16571, 28862, 92360, 55496, 2252, 49357, 88279, 116954, 47327, 61671, 108784, 59635, 88309, 20730, 47363, 102660, 98573, 78094, 14617, 59673, 2335, 45350, 31015, 55599, 71989, 86355, 16726, 51558, 84329, 78188, 90481, 33141, 63873, 18818, 70035, 102808, 29086, 104871, 111027, 80309, 39355, 10691, 39375, 473, 76256, 102880, 66018, 35306, 2549, 92661, 100861, 49663, 102917, 49672, 2571, 119313, 4626, 29212, 10786, 27174, 70183, 55851, 119341, 86575, 6707, 90685, 82495, 35394, 23111, 10831, 601, 33373, 53858, 76398, 86646, 60035, 105094, 27278, 2732, 76462, 82614, 109252, 2757, 39635, 109268, 41690, 99034, 103133, 101088, 76513, 23266, 66283, 8947, 70391, 99069, 29445, 56070, 109317, 29448, 84752, 17170, 70419, 31513, 90915, 119597, 19247, 13112, 68415, 103237, 66375, 76616, 76623, 90963, 853, 35670, 4963, 41828, 54131, 13178, 64379, 111487, 103301, 64393, 60300, 109453, 25488, 29584, 39832, 74653, 58270, 86944, 25509, 66477, 7098, 72635, 109508, 99270, 52167, 99278, 117713, 48087, 84952, 46042, 48091, 25573, 89064, 5098, 48108, 64493, 19442, 52217, 37884, 84992, 107521, 33793, 15363, 27655, 109576, 117770, 39946, 37901, 21527, 15392, 1062, 76839, 85046, 111672, 107578, 31806, 101454, 40021, 5208, 62555, 17500, 117886, 64642, 107651, 13452, 107666, 93336, 81052, 52384, 25771, 60590, 109742, 83124, 101561, 64701, 42173, 91333, 44247, 36063, 77026, 21733, 25831, 60654, 68854, 23804, 40208, 54545, 120082, 79125, 103702, 52505, 54554, 89371, 60704, 27938, 13605, 9510, 120115, 93496, 111931, 101698, 95562, 21835, 66892, 66904, 38236, 48477, 30045, 54622, 52579, 5478, 77170, 32118, 30077, 101758, 81280, 120194, 105866, 46474, 109971, 11671, 15768, 116121, 52636, 99752, 28079, 40373, 81335, 73147, 17858, 89538, 11717, 44488, 105930, 38350, 7633, 118235, 114146, 97763, 77284, 34275, 5607, 60906, 7661, 62964, 15860, 9720, 44548, 91655, 75275, 7694, 120347, 58907, 77348, 28197, 32296, 28202, 120372, 77375, 30272, 40513, 104003, 77380, 61000, 75338, 44621, 15953, 65105, 15966, 30303, 52832, 9830, 95852, 83566, 101999, 104046, 102011, 7806, 75398, 13962, 108173, 73365, 81564, 120480, 75436, 93871, 34480, 71346, 16051, 5812, 5817, 28351, 79554, 22212, 77511, 75464, 24269, 108241, 7890, 46803, 63185, 83669, 108246, 7891, 30420, 55000, 9950, 87778, 63209, 1771, 1776, 24305, 100084, 22261, 38646, 38649, 24322, 83719, 24327, 26375, 120591, 26386, 112421, 116519, 5929, 53035, 22315, 59187, 110389, 30530, 44867, 48965, 51023, 44881, 61288, 46961, 24438, 40843, 100236, 110479, 44948, 87958, 100260, 24499, 26552, 51129, 83905, 108483, 75720, 16330, 51150, 14290, 14291, 4053, 92124, 45030, 94183, 12265, 55273, 96237, 20476, 28670]

In [7]:
np.sort(all_entities_one_hop_1)

array([   34,   269,   282,   382,   433,   766,   963,  1056,  1190,
        1580,  1615,  1621,  1704,  1807,  1826,  1882,  2063,  2432,
        2437,  2924,  3100,  3249,  3949,  4607,  4828,  4851,  4953,
        5013,  5270,  5501,  5519,  5651,  5685,  5859,  6081,  6204,
        6281,  6647,  6969,  7257,  7358,  7366,  7407,  7427,  7547,
        7550,  7939,  8372,  8810,  8854,  8890,  8920,  9174,  9482,
       10433, 10491, 11008, 11573, 11674, 11782, 12218, 12276, 12322,
       12606, 12964, 13111, 13127, 13163, 13534, 14061, 14379, 14538,
       14660, 14663, 14872, 14928, 14940, 14971, 15127, 15887, 16033,
       16042, 16331, 16338, 16375, 16664, 17688, 17808, 17902, 18367,
       18368, 18371, 18580, 19422, 19707, 19844, 20039, 20158, 20160,
       20599, 20717, 20754, 20814, 21446, 21455, 21485, 21532, 21789,
       22422])

In [9]:
print(len(all_entities_one_hop_1))

109


In [26]:
np.sort(all_triples_one_hop)

array([   473,    601,    853,   1062,   1771,   1776,   2052,   2252,
         2335,   2549,   2571,   2732,   2757,   4053,   4626,   4963,
         5098,   5208,   5478,   5607,   5812,   5817,   5929,   6265,
         6707,   7098,   7633,   7661,   7694,   7806,   7890,   7891,
         8947,   9510,   9720,   9830,   9950,  10691,  10786,  10831,
        11671,  11717,  12265,  13112,  13178,  13452,  13605,  13962,
        14290,  14291,  14428,  14455,  14617,  15363,  15392,  15768,
        15860,  15953,  15966,  16051,  16330,  16443,  16571,  16726,
        17170,  17500,  17858,  18818,  19247,  19442,  20476,  20730,
        21527,  21733,  21835,  22212,  22261,  22315,  22604,  23111,
        23266,  23804,  24269,  24305,  24322,  24327,  24438,  24499,
        25488,  25509,  25573,  25771,  25831,  26375,  26386,  26552,
        26658,  27174,  27278,  27655,  27938,  28079,  28197,  28202,
        28351,  28670,  28862,  29086,  29212,  29445,  29448,  29584,
      

In [8]:
np.sort(all_entities_one_hop_2)

array([  362,   659,   942,  1280,  1394,  1472,  1606,  1722,  1798,
        1802,  1807,  2001,  2002,  2541,  2681,  2826,  2846,  3078,
        3487,  3557,  3571,  3609,  3880,  3882,  4154,  4402,  4851,
        4932,  5232,  5478,  5800,  5825,  6055,  6253,  6349,  6391,
        6491,  6678,  6976,  7189,  7523,  7939,  8360,  8488,  8545,
        8967,  9075,  9136,  9548,  9552,  9752, 10083, 10419, 10558,
       11450, 11582, 11729, 11761, 11879, 12218, 12509, 12514, 12515,
       12529, 12731, 12866, 13003, 13182, 13385, 13684, 13796, 13804,
       14042, 14062, 14236, 14247, 14304, 14379, 14409, 14462, 14538,
       14599, 14760, 14801, 14950, 14971, 15413, 15433, 15904, 16028,
       16196, 16205, 16744, 16957, 16988, 17116, 17564, 17645, 17685,
       17985, 18025, 18042, 18366, 18368, 18405, 18713, 18869, 19031,
       19107, 19142, 19351, 19390, 19423, 19685, 19958, 20026, 20039,
       20289, 20571, 20650, 20994, 21023, 21601, 21737, 21803, 21894])

In [27]:
print(len(all_triples_one_hop))

407


In [10]:
print(len(all_entities_one_hop_2))

126


In [13]:
is_inference = None
if is_inference != None:
    print('go')
    

In [22]:
import requests
data_dir = "D:\\13.PURDUE\\Data\\ConceptFlow(ECCF)_data"
with open('%s/resource.txt' % data_dir) as f:
    d = json.loads(f.readline())

    csk_triples = d['csk_triples']
    csk_entities = d['csk_entities']
    raw_vocab = d['vocab_dict']
    kb_dict = d['dict_csk']
    dict_csk_entities = d['dict_csk_entities']
    dict_csk_triples = d['dict_csk_triples']

def query_conceptnet(keyword):
    url = f"http://api.conceptnet.io/c/en/{keyword}?limit=100"
    response = requests.get(url)
    return response.json()

def extract_data(concept_data):
    entities = set()
    triples = []
    for edge in concept_data['edges']:
        start = edge['start']['@id'].split('/')[-1]
        end = edge['end']['@id'].split('/')[-1]
        rel = edge['rel']['@id'].split('/')[-1]
        triples.append((start, rel, end))
        entities.update([start, end])
    return entities, triples

def generate_response_format(entities, triples):
    # Simulate entity and triple index mapping
    entity2id = {entity: idx for idx, entity in enumerate(entities)}
    triple_indices = range(len(triples))  # Assuming each triple gets a unique index

    data_format = {
        "all_entities_one_hop": list(entity2id.values()),
        "post_triples": list(triple_indices),  # Example: every triple is used
        "post": ["This", "is", "an", "example", "post", "."],
        "response": ["This", "is", "an", "example", "response", "."],
        "match_response_index_one_hop": [-1] * len(entity2id),  # Simplified example
        "only_two": list(entity2id.values())[::2],  # Every second entity for example
        "match_response_index_only_two": [-1] * len(entity2id),  # Simplified example
        "all_triples_one_hop": list(triple_indices)  # Simplified example
    }
    return data_format

def main(question):
    keywords = question.split()  # Simple keyword extraction from the question
    all_entities = set()
    all_triples = []

    for keyword in keywords:
        concept_data = query_conceptnet(keyword)
#         print('concept_data',concept_data)
        entities, triples = extract_data(concept_data)
        print('entities', entities)
        print('triples', triples)
        all_entities.update(entities)
        all_triples.extend(triples)

    formatted_data = generate_response_format(all_entities, all_triples)
    print(formatted_data)

# Example usage
main("What is related to coffee?")

entities set()
triples []
entities {'é', 'es', 'ei_ole', 'どす', 'є', "she'sn't", 'en_1', 'r', 'е', 'と言うのは', 'infinite_stratos', 'has', 'mura', 'expensive', 'e', '3', 'está', 'jeste', 'inar', 'これはなんですか', 'ドス', 'cérb', 'trínarb', 'tabansızsa', 'αληθώσ_ανέστη', 'ist', 'evse', 'ialah', 'يكون', 'beeth', 'yw', "it's", '𐌹𐍃𐍄', 'being', 'isness', 'ειναι', 'だ', '是', 'wast', 'thì', 'nĩ', 'v', 'зарем', 'n', 'ってのは', 'oes', 'id', 'isentropic', 'じゃ', 'je', 'です', 'computing', 'ónar', 'IS_(Infinite_Stratos)', 'qu_est_ce_que_c_est', 'átʼéii', 'bes', 'jest', 'er', '𐬀𐬯𐬙𐬌', 'bilgisayarsa', 'ما_هذا', 'でげす', 'sta', 'found_in_subway', 'adalah', 'ざり', 'で御座います', 'っす', 'is', "who's", 'már_késő_van', 'a', 'で御座ります', 'いらっしゃる', "where's", 'dar', 'beest', 'でごんす', 'єстъ', 'ada_apa', 'your+name+is+mud-p#Component-3'}
triples [('どす', 'Synonym', 'is'), ('n', 'Synonym', 'is'), ('en_1', 'RelatedTo', 'is'), ('ざり', 'Synonym', 'is'), ('is', 'Synonym', 'jest'), ('ドス', 'Synonym', 'is'), ('いらっしゃる', 'Synonym', 'is'), ('is', 'Synon

In [23]:
import requests

def get_one_hop_relations(concept):
    url = f"http://api.conceptnet.io/c/en/{concept}"
    response = requests.get(url)
    data = response.json()
    
    relations = []
    for edge in data['edges']:
        start = edge['start']['label']
        rel = edge['rel']['label']
        end = edge['end']['label']
        relations.append((start, rel, end))
    
    return relations

# Example usage
concept = "coffee"
one_hop_relations = get_one_hop_relations(concept)
for relation in one_hop_relations:
    print(relation)

('coffee', 'IsA', 'a stimulant')
('Coffee', 'HasA', 'caffeine')
('Coffee', 'HasProperty', 'served hot')
('Café', 'Synonym', 'coffee')
('coffee', 'AtLocation', 'a coffee shop')
('a sugar', 'AtLocation', 'coffee')
('a mug', 'UsedFor', 'coffee')
('Coffee', 'ReceivesAction', 'made from coffee beans')
('sugar', 'RelatedTo', 'coffee')
('caffè', 'Synonym', 'coffee')
('ต้นกาแฟ', 'Synonym', 'coffee')
('kawa', 'Synonym', 'coffee')
('kahva', 'RelatedTo', 'coffee')
('コーヒーブラウン', 'Synonym', 'coffee')
('قَهْوَة', 'Synonym', 'coffee')
('café', 'Synonym', 'coffee')
('coffee', 'IsA', 'a popular drink')
('coffee', 'AtLocation', 'a internet cafe')
('kopi', 'Synonym', 'coffee')
('kaffe', 'Synonym', 'coffee')


In [24]:
import requests

def get_relations(concept):
    url = f"http://api.conceptnet.io/c/en/{concept}"
    response = requests.get(url)
    data = response.json()
    
    relations = []
    for edge in data['edges']:
        relations.append({
            'start': edge['start']['label'],
            'rel': edge['rel']['label'],
            'end': edge['end']['label']
        })
    return relations

def get_two_hop_relations(concept):
    # First hop
    first_hop_relations = get_relations(concept)
    all_relations = first_hop_relations.copy()

    # Second hop
    for relation in first_hop_relations:
        second_hop_relations = get_relations(relation['end'])
        all_relations.extend(second_hop_relations)
    
    return all_relations

# Example usage
concept = "coffee"
two_hop_relations = get_two_hop_relations(concept)
for relation in two_hop_relations:
    print(relation)

{'start': 'coffee', 'rel': 'IsA', 'end': 'a stimulant'}
{'start': 'Coffee', 'rel': 'HasA', 'end': 'caffeine'}
{'start': 'Coffee', 'rel': 'HasProperty', 'end': 'served hot'}
{'start': 'Café', 'rel': 'Synonym', 'end': 'coffee'}
{'start': 'coffee', 'rel': 'AtLocation', 'end': 'a coffee shop'}
{'start': 'a sugar', 'rel': 'AtLocation', 'end': 'coffee'}
{'start': 'a mug', 'rel': 'UsedFor', 'end': 'coffee'}
{'start': 'Coffee', 'rel': 'ReceivesAction', 'end': 'made from coffee beans'}
{'start': 'sugar', 'rel': 'RelatedTo', 'end': 'coffee'}
{'start': 'caffè', 'rel': 'Synonym', 'end': 'coffee'}
{'start': 'ต้นกาแฟ', 'rel': 'Synonym', 'end': 'coffee'}
{'start': 'kawa', 'rel': 'Synonym', 'end': 'coffee'}
{'start': 'kahva', 'rel': 'RelatedTo', 'end': 'coffee'}
{'start': 'コーヒーブラウン', 'rel': 'Synonym', 'end': 'coffee'}
{'start': 'قَهْوَة', 'rel': 'Synonym', 'end': 'coffee'}
{'start': 'café', 'rel': 'Synonym', 'end': 'coffee'}
{'start': 'coffee', 'rel': 'IsA', 'end': 'a popular drink'}
{'start': 'coffee